- hosts: terraform-ansible
  tasks:
  - name: create index file
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Hello World</h1>
  - name: create http server
    shell: "nohup busybox httpd -f -p 8080 &"