- hosts: terraform-ansible
  tasks:
  - name: Install python and virtualenv
    apt:
      pkg: 
        - python3
        - virtualenv
      update_cache: yes
    become: yes

  - name: Install dependencies with pip (Django and Django Rest)
    pip:
      virtualenv: /home/ubuntu/venv
      name:
        - django
        - djangorestframework
      
  - name: Start project
    shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu'

  - name: Include hosts in settings
    lineinfile:
      path: /home/ubuntu/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes

