- hosts: terraform-ansible
  tasks:
  - name: Install python and virtualenv
    apt:
      pkg: 
        - python3
        - virtualenv
      update_cache: yes
    become: yes

  - name: Install dependencies with pip (Django and Django Rest)
    pip:
      virtualenv: /home/ubuntu/venv
      name:
        - django
        - djangorestframework
