- hosts: dev
  vars:
    app_path: /home/ubuntu/api

  tasks:
    - name: Install python and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: true

    - name: Install dependencies with pip (Django and Django Rest)
      pip:
        virtualenv: "{{app_path}}/venv"
        name:
          - django
          - djangorestframework

    - name: Check if project exists
      stat:
        path: "{{app_path}}/setup/settings.py"
      register: project

    - name: Start project
      shell: ". {{app_path}}/venv/bin/activate; django-admin startproject setup {{app_path}}"
      when: not project.stat.exists

    - name: Include hosts in settings
      lineinfile:
        path: "{{app_path}}/setup/settings.py"
        regexp: "ALLOWED_HOSTS"
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
